### ISSUE TITLE
SNSでシェアしたときのタイトル

### ISSUE THREAD

**Issue by ksss** [ko1/tokyo11#26]
例えば http://regional.rubykaigi.org/tokyo11/schedule/ をtwitter等でシェアした時に、titleタグを引いてサイトのタイトルが`Schedule`となってしまい、何のサイトへのリンクなのかわかりにくくなっていると思います。

https://twitter.com/search?f=tweets&vertical=default&q=http%3A%2F%2Fregional.rubykaigi.org%2Ftokyo11%2Fschedule%2F&src=typd

サイトのtitleを`TokyoRubyKaigi11/Schedule`などにして、なんのサイトへのリンクなのかわかりやすくするのはどうでしょうか？(やりかたがちょっとわからなかったです……。)

**Comment by ko1** [comment]
@yuki24 こんな感じでやってみましたが、どうでしょう。

**Comment by yuki24** [comment]
いい感じだと思います。Open Graph のメタタグも設定してこんな感じで表示されるようにしました。そろそろ翻訳をうまく表示するのが辛くなってきた…

### Twitter:

![screen shot 2016-04-04 at 8 14 45 pm](https://cloud.githubusercontent.com/assets/386234/14246444/13a67182-faa2-11e5-85a8-87f56d62ff2e.png)

### Facebook:

![screen shot 2016-04-04 at 8 15 46 pm](https://cloud.githubusercontent.com/assets/386234/14246445/13a67e7a-faa2-11e5-9e02-3151061e6363.png)
